#include "M_Character.h"


#include "GameFramework/SpringArmComponent.h"//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É±Û¿ï¿½ï¿½ï¿½
#include "GameFramework/CharacterMovementComponent.h"//ï¿½ï¿½É«ï¿½Æ¶ï¿½ï¿½ï¿½ï¿½ï¿½

#include "Camera/CameraComponent.h"//ï¿½ï¿½ï¿½ï¿½ï¿½

#include "Components/InputComponent.h"//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
#include "Components/SkeletalMeshComponent.h"//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
#include "Components/SceneComponent.h"//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½

#include "M_PlayerState.h"

#include "Kismet/GameplayStatics.h"//ï¿½ï¿½Ì¬ï¿½ï¿½ï¿½ß°ï¿½ï¿½ï¿½Ê§È¥ï¿½ï¿½ï¿½ï¿½ï¿½Ã¿ï¿½ï¿½Ü»ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ó£¨¾ï¿½ï¿½ï¿½Î´ï¿½Ë½â£©
#include "Engine.h"


//ï¿½Ü½á£º
/*
1.ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½-Êµï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ã¡ï¿½
2.ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½-Êµï¿½Ö»ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
3.ï¿½ï¿½È¡ï¿½ï¿½ï¿½Ãµï¿½Ö¸ï¿½ë£¬ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½C++ï¿½ï¿½ï¿½ï¿½Í¼ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ý¡ï¿½
ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
	Êµï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
	ï¿½ï¿½È¡ï¿½ï¿½Òªï¿½ï¿½Í¼ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ã£ï¿½ï¿½ç·¢ï¿½ï¿½Ä²ï¿½ï¿½Ô¹ï¿½ï¿½ï¿½
BeginPlay
	ï¿½ï¿½È¡ControllerÖ¸ï¿½ï¿½
ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Êµï¿½Ö£ï¿½ï¿½Æ¶ï¿½ï¿½ï¿½Fireï¿½ï¿½Meditationï¿½ï¿½
	Movement BaseÏµï¿½ï¿½
	FireÏµï¿½ï¿½
	MeditationÏµï¿½ï¿½

ï¿½ï¿½Characterï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Í¨ï¿½ï¿½ï¿½åµ¥ï¿½ï¿½
Í¨ï¿½ï¿½ï¿½ï¿½ï¿½Ã²ï¿½Ñ¯ï¿½ï¿½ SP~ï¿½ï¿½SPControllerï¿½ï¿½
Í¨ï¿½Å½Ó¿Ú£ï¿½ï¿½ï¿½ï¿½Þ£ï¿½

Í¨ï¿½ï¿½ï¿½ï¿½ï¿½Ý£ï¿½
ï¿½ï¿½Ê¹ï¿½Ã¼ï¿½ï¿½ï¿½Ê±ï¿½ï¿½ï¿½Þ¸ï¿½PlayerStateï¿½ÐµÄ±ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Öµï¿½ï¿½Ä§ï¿½ï¿½Öµï¿½ï¿½
ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É¡ï¿½ï¿½Ú´ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö·ï¿½æ´¢
ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É¡ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ëºï¿½ï¿½ï¿½ï¿½Ó´ï¿½ï¿½ï¿½ï¿½Ëºï¿½ï¿½Â¼ï¿½
ï¿½ï¿½ï¿½ï¿½ï¿½Ú¡ï¿½ï¿½Ü´æµµÏµÍ³ï¿½ë±³ï¿½ï¿½ÏµÍ³ï¿½ï¿½Buff

*/
AM_Character::AM_Character()
{  
	

	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Íµï¿½ï¿½É±ï¿½
	CameraArm = CreateDefaultSubobject<USpringArmComponent>(TEXT("CameraArm"));
	CameraArm->SetupAttachment(GetMesh());
	CameraArm->bUsePawnControlRotation = true;

	// Create a CameraComponent	
	Camera = CreateDefaultSubobject<UCameraComponent>(TEXT("Camera"));
	Camera->SetupAttachment(CameraArm);
	Camera->SetRelativeLocation(FVector(0, 0, BaseEyeHeight),false); // Position the camera
	CameraArm->bUsePawnControlRotation = false;

<<<<<<< Updated upstream
	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
	CharacterMesh = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("CharacterMesh"));
	CharacterMesh->SetupAttachment((USceneComponent*)GetCapsuleComponent());
=======
	//´´½¨»ù±¾¹Ç÷ÀÍø¸ñÌå×é¼þ
	MagicSlotComponent = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("MagicSlotComponent"));
	MagicSlotComponent->SetupAttachment(CameraArm);
>>>>>>> Stashed changes

	//RootComponent = CharacterMesh;//ï¿½ï¿½Ò»ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Îªï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Meshï¿½ï¿½ï¿½ï¿½ï¿½Ú¸ï¿½ï¿½ï¿½ï¿½ï¿½Ï»ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ï£ï¿½

	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ãªï¿½ï¿½ï¿½ï¿½ï¿½
	MagicSlotComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("EffectSlot"));
	MagicSlotComponent->CastShadow = false;
	//MagicSlotComponent->SetUpAttachment(GetCapsuleComponent());
	//CharacterMesh->SetSimulatePhysics(true);//ï¿½ï¿½ï¿½ï¿½Ä£ï¿½ï¿½Ç³ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü£ï¿½ï¿½ï¿½ï¿½ï¿½Òªï¿½ï¿½Ê±ï¿½ï¿½Òªï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê±ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ð§ï¿½ï¿½ï¿½ï¿½ï¿½Ô¿ï¿½ï¿½ï¿½ï¿½ï¿½


	//C++ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Í¼ï¿½ï¿½ï¿½ï¿½1ï¿½ï¿½ï¿½ï¿½È¡ï¿½ï¿½ï¿½ï¿½ï¿½Í¼ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½,ï¿½ï¿½ï¿½ÍºÍ¶ï¿½ï¿½ï¿½
	static ConstructorHelpers::FClassFinder<AActor> BP_ActorMatch(TEXT("Blueprint'/Game/BluePrint/Skill/BPM_MagicBullet.BPM_MagicBullet_C'"));
	if (BP_ActorMatch.Succeeded()) { MatchBPMgaicActor = BP_ActorMatch.Class; }

	static ConstructorHelpers::FObjectFinder<UClass> BP_ClassFinder(TEXT("Blueprint'/Game/BluePrint/Skill/BPM_MagicBullet.BPM_MagicBullet_C'"));
	if (BP_ClassFinder.Object) { UClass* bpClass = BP_ClassFinder.Object; }

}
void AM_Character::BeginPlay()
{
	Super::BeginPlay();

	//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö¸ï¿½ï¿½Îªï¿½ï¿½,ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
	SPController = Cast<AM_Controller>(UGameplayStatics::GetPlayerController(GetWorld(), 0));

}
void AM_Character::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent) 
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);

	check(PlayerInputComponent);
	//ï¿½ó¶¨ºï¿½ï¿½ï¿½
	PlayerInputComponent->BindAxis("MoveForward", this, &AM_Character::MoveForward);
	PlayerInputComponent->BindAxis("MoveLeft", this, &AM_Character::MoveLeft);
	PlayerInputComponent->BindAxis("LookUp", this, &AM_Character::LookUp);
	PlayerInputComponent->BindAxis("LookRight", this, &AM_Character::LookRight);
	PlayerInputComponent->BindAction("Jump", IE_Pressed, this, &AM_Character::OnStartJump);
	PlayerInputComponent->BindAction("Jump", IE_Released, this, &AM_Character::OnStopJump);
	PlayerInputComponent->BindAction("Fire", IE_Pressed, this, &AM_Character::Fire);
}

//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Îªï¿½ï¿½ï¿½ï¿½ï¿½é£º
void AM_Character::MoveForward(float value)
{
	if (value != 0.f && Controller) {
		const FRotator Rotation = Controller->GetControlRotation();
		FVector Direction = FRotationMatrix(Rotation).GetScaledAxis(EAxis::X);
		AddMovementInput(Direction, value);
	}
}
void AM_Character::MoveLeft(float value)
{
	if (value != 0.f && Controller) {
		const FQuat Rotation = GetActorQuat();
		FVector Direction = FQuatRotationMatrix(Rotation).GetScaledAxis(EAxis::Y);
		AddMovementInput(Direction, value);
	}
}
void AM_Character::LookUp(float value)
{
	if (value != 0 && Controller)
	{
		AddControllerPitchInput(value);
	}
}
void AM_Character::LookRight(float value)
{
	if (value != 0 && Controller)
	{
		AddControllerYawInput(value);
	}
}
void AM_Character::OnStartJump()
{
	bPressedJump = true;
}
void AM_Character::OnStopJump()
{
	bPressedJump = false;
	StopJumping();
}
void AM_Character::Fire()
{
	if (MatchBPMgaicActor)
	{
		//ï¿½ï¿½È¡ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
		FVector MuzzleLocation = MagicSlot->GetComponentLocation();
		FRotator MuzzleRotation = Controller->GetControlRotation();
		GetWorld()->SpawnActor<AM_MagicBullet>(MatchBPMgaicActor,MuzzleLocation, MuzzleRotation);


		
		if (SPController->SPState) 
		{
			SPController->SPState->OnCostMana(100); 
			GEngine->AddOnScreenDebugMessage(-1, 1.f, FColor::Red, TEXT("fire Cost! Mana"));
		}

	}

}
bool AM_Character::IsDead()
{
	if (SPController->SPState) return SPController->SPState->IsPlayerDead();
	return false;
}
void AM_Character::AcceptDamage(int DamageVal)
{
    //if (SPController->SPState) SPController->SPState->AcceptDamage(DamageVal);
}
